### ISSUE TITLE
Crashes when saving draft encoded with UTF-8

### ISSUE THREAD

**Issue by avtobiff** [sup-heliotrope/sup#340]
When trying to save a draft encoded with UTF-8 Sup crashes.

```
[2014-10-21 11:38:30 +0200] ERROR: oh crap, an exception                                                       
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/avtobiff/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- ArgumentError from thread: main
invalid byte sequence in UTF-8
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:672:in `gsub'
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:672:in `sanitize_body'
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:630:in `write_message'
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:549:in `block in save_as_draft'
/usr/lib/ruby/vendor_ruby/sup/draft.rb:19:in `block in write_draft'
/usr/lib/ruby/vendor_ruby/sup/draft.rb:19:in `open'
/usr/lib/ruby/vendor_ruby/sup/draft.rb:19:in `write_draft'
/usr/lib/ruby/vendor_ruby/sup/util.rb:658:in `method_missing'
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:549:in `save_as_draft'
/usr/lib/ruby/vendor_ruby/sup/mode.rb:59:in `handle_input'
/usr/lib/ruby/vendor_ruby/sup/buffer.rb:222:in `handle_input'
/usr/bin/sup-mail:270:in `<module:Redwood>'
/usr/bin/sup-mail:74:in `<main>'

**Comment by gauteh** [comment]
Closing, need more info or issue is fixed.
