### ISSUE TITLE
Cannot add sources with spaces

### ISSUE THREAD

**Issue by tyrion** [sup-heliotrope/sup#374]
```
tyrion@acerone:~/.sup$ sup-add "maildir:/home/tyrion/.Mail/account/Sent Items"                                                                                            
[2015-01-08 00:24:09 +0100] Flushing Xapian updates to disk. This may take a while...
/home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): maildir:/home/tyrion/.Mail/account/Sent Items (URI::InvalidURIError)
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:98:in `block in <top (required)>'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:90:in `each'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:90:in `<top (required)>'
        from /home/tyrion/.rbenv/versions/2.1.3/bin/sup-add:23:in `load'
        from /home/tyrion/.rbenv/versions/2.1.3/bin/sup-add:23:in `<main>'
```

**Comment by maxmeyer** [comment]
Try %20 instead of " ".

**Comment by gauteh** [comment]
Should be fixed.
