### ISSUE TITLE
exception running sup-sync-back-maildir

### ISSUE THREAD

**Issue by kols** [sup-heliotrope/sup#406]
```
$ sup-sync-back-maildir                                                                                                                                                                                       
/Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
Are you sure you want to synchronize 'maildir:/Users/kane/mail/work/archive'? (Y/n) y
/Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:98: warning: Enumerator.new without a block is deprecated; use Object#to_enum
Synchronizing 'maildir:/Users/kane/mail/work/archive'... 0%[2015-03-23 19:00:35 +0800] Flushing Xapian updates to disk. This may take a while...
/Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:615:in `find_docid': unhandled exception
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:620:in `find_doc'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:630:in `get_entry'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:236:in `block in build_message'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:639:in `synchronize'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:236:in `build_message'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:301:in `block in each_message'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:288:in `block in each_id'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:288:in `each'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:288:in `each_id'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:300:in `each_message'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:102:in `block (2 levels) in <top (required)>'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:100:in `each'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:100:in `block in <top (required)>'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:92:in `each'
	from /Users/kane/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:92:in `<top (required)>'
	from /Users/kane/.rbenv/versions/2.2.1/bin/sup-sync-back-maildir:23:in `load'
	from /Users/kane/.rbenv/versions/2.2.1/bin/sup-sync-back-maildir:23:in `<main>'
```

**Comment by kols** [comment]
ok again after removing `~/.sup/xapian` folder and rebuild the index
