### ISSUE TITLE
Add documentation on the wiki about the psych issue.

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/sup#410]
I am having issues editing the wiki for some reason. So here it goes a patch made with ``git format-patch``

```patch
From 3e67cf95c65b908c62f3658e79eb68ab582ef08d Mon Sep 17 00:00:00 2001
From: Alfredo Palhares <masterkorp@masterkorp.net>
Date: Mon, 30 Mar 2015 11:32:41 +0100
Subject: [PATCH] Add documentation about the psych module conflict

---
 Home.md                  |  1 +
 YAML-error-on-startup.md | 26 ++++++++++++++++++++++++++
 2 files changed, 27 insertions(+)
 create mode 100644 YAML-error-on-startup.md

diff --git a/Home.md b/Home.md
index c933be7..c4a5d05 100644
--- a/Home.md
+++ b/Home.md
@@ -82,6 +82,7 @@ Note that installing sup via both your native package manager and using instruct
 
 * [[UTF-8 issues]]
 * [[CtrlY]]
+* [[YAML-error-on-startup]]
 
 ## Sup development
 
diff --git a/YAML-error-on-startup.md b/YAML-error-on-startup.md
new file mode 100644
index 0000000..e32a55b
--- /dev/null
+++ b/YAML-error-on-startup.md
@@ -0,0 +1,26 @@
+# YAML error while starting sup
+
+Usually after a ``gem update`` you might see this error when starting sup:
+
+```ruby
+$ sup
+/home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:30:in `yaml_properties': undefined method `yaml_tag' for Redwood::MBox:Class (NoMethodError)
+    from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:10:in `<class:MBox>'
+    from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:6:in `<module:Redwood>'
+    from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:4:in `<top (required)>'
+    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
+    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
+    from /home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:423:in `<top (required)>'
+    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
+    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
+    from /home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/bin/sup:21:in `<top (required)>'
+    from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `load'
+    from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `<main>'
+```
+
+The current fix is to remove the ``psych`` gem.
+
+References:
+
+- [#403 - Updated gems. Sup now crashes with an error about "undefined method" 'yaml_tag'](https://github.com/sup-heliotrope/sup/issues/403)
+- [#409 - `yaml_properties': undefined method `yaml_tag' ](https://github.com/sup-heliotrope/sup/issues/409#event-266815826)
-- 
2.3.4
```

Regards,
Alfredo Palhares

**Comment by ZJvandeWeg** [comment]
:+1:
I've just added these though the web UI.

**Comment by masterkorp** [comment]
@ZJvandeWeg Thank you.

I will be closing this issue.
