### ISSUE TITLE
NoMethodError from thread: user-invoked poll

### ISSUE THREAD

**Issue by maxmeyer** [sup-heliotrope/sup#430]
I'm not able to tell what I did. I pressed some buttons by accident.

```
--- NoMethodError from thread: user-invoked poll
undefined method `write' for nil:NilClass
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:238:in `block in draw_line_from_array'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:224:in `each'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:224:in `each_with_index'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:224:in `draw_line_from_array'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:199:in `draw_line'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/line_cursor_mode.rb:52:in `draw_line'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:46:in `block in draw'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:46:in `each'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/scroll_mode.rb:46:in `draw'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/line_cursor_mode.rb:37:in `draw'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/buffer.rb:60:in `draw'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/buffer.rb:44:in `redraw'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/buffer.rb:284:in `draw_screen'
(eval):1:in `draw_screen'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:201:in `handle_added_update'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/update.rb:26:in `block in relay'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/update.rb:26:in `each'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/update.rb:26:in `relay'
(eval):1:in `relay'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:228:in `block in poll_from'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/maildir.rb:161:in `block in poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each_with_index'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:201:in `poll_from'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:136:in `each'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:136:in `block in do_poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:135:in `synchronize'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:135:in `do_poll'
(eval):1:in `do_poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/modes/poll_mode.rb:15:in `poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:58:in `poll_with_sources'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup/poll.rb:94:in `poll'
(eval):1:in `poll'
/home/user/.gem/2.2.2/gems/sup-0.21.0/bin/sup:314:in `block in <module:Redwood>'
/home/user/.gem/2.2.2/gems/sup-0.21.0/lib/sup.rb:88:in `block in reporting_thread'
```

**Comment by gauteh** [comment]
Probably related to #372.

**Comment by gauteh** [comment]
Closing as duplicate, please continue discussion there. Also probably similar to the buffer dirty issues from earlier.
