### ISSUE TITLE
DatabaseCorruptError: Db block overwritten - are there multiple writers? (IOError)

### ISSUE THREAD

**Issue by mfournier** [sup-heliotrope/sup#446]
Hello,

I'm getting the following exception when running `sup-sync -v`:
```
Adding new message maildir:/home/marc/mailinglists/heka/#new/1435581967.28728_165.host with labels heka,unread,inbox
/home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:727:in `replace_document': DatabaseCorruptError: Db block overwritten - are there multiple writers? (IOError)
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:727:in `block in sync_message'
        from /home/marc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:639:in `synchronize'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:721:in `sync_message'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/poll.rb:215:in `block in poll_from'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
        from (eval):1:in `poll_from'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:124:in `block in <top (required)>'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:119:in `each'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:119:in `<top (required)>'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/sup-sync:23:in `load'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/sup-sync:23:in `<main>'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/ruby_executable_hooks:15:in `eval'
        from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/ruby_executable_hooks:15:in `<main>'
```

What puzzles me and makes me believe there isn't actually any database corruption, is that when I remove the file referred to just before the crash from the Maildir, `sup-sync` completes successfully, and sup also runs just fine.

Here is the exact content of this problematic `1435581967.28728_165.host` email:
```
Return-Path: <rmiller@mozilla.com>
X-Original-To: heka@mozilla.org
Delivered-To: heka@mailman1.mail.corp.phx1.mozilla.com
Received: from smtp.mozilla.org (mx2.mail.corp.phx1.mozilla.com [10.20.77.62])
	by mailman1.mail.corp.phx1.mozilla.com (Postfix) with ESMTP id
	6A5C8F2389
	for <heka@mozilla.org>; Mon, 17 Mar 2014 14:32:56 -0700 (PDT)
Received: from [192.168.42.91] (75-101-48-171.dsl.static.sonic.net
	[75.101.48.171]) (Authenticated sender: rmiller@mozilla.com)
	by mx2.mail.corp.phx1.mozilla.com (Postfix) with ESMTPSA id 29FE0F2389; 
	Mon, 17 Mar 2014 14:32:56 -0700 (PDT)
Message-ID: <53276A07.7040208@mozilla.com>
Date: Mon, 17 Mar 2014 14:32:55 -0700
From: Rob Miller <rmiller@mozilla.com>
User-Agent: Mozilla/5.0 (X11; Linux x86_64;
	rv:24.0) Gecko/20100101 Thunderbird/24.2.0
MIME-Version: 1.0
To: Dan <danharvey42@gmail.com>
References: <CA+1-bOFGd0y0LC8XQs37qsuJR0jGUhk2L5r-_b2Qp6mBknK2pA@mail.gmail.com>
	<53161112.5000703@mozilla.com>
	<CA+1-bOFYuQ2YTz15GzR4cv0bWFAMU11gCjiyytESq+H34fhMGg@mail.gmail.com>
In-Reply-To: <CA+1-bOFYuQ2YTz15GzR4cv0bWFAMU11gCjiyytESq+H34fhMGg@mail.gmail.com>
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit
Cc: heka@mozilla.org
Subject: Re: [heka] S3 output plugin
X-BeenThere: heka@mozilla.org
X-Mailman-Version: 2.1.15
Precedence: list
List-Id: "Heka is Mozilla's large-scale data gathering infrastructure."
	<heka.mozilla.org>
List-Unsubscribe: <https://mail.mozilla.org/options/heka>,
	<mailto:heka-request@mozilla.org?subject=unsubscribe>
List-Archive: <http://mail.mozilla.org/pipermail/heka/>
List-Post: <mailto:heka@mozilla.org>
List-Help: <mailto:heka-request@mozilla.org?subject=help>
List-Subscribe: <https://mail.mozilla.org/listinfo/heka>,
	<mailto:heka-request@mozilla.org?subject=subscribe>
X-List-Received-Date: Mon, 17 Mar 2014 21:32:56 -0000
Content-Length: 4638
Lines: 118

On Mon 17 Mar 2014 01:30:10 PM PDT, Dan wrote:
> Thanks for the reply, we're starting with just focusing on output to
> Carbon but will look at something like this when we get there now we
> know what's possible.
>
> Another related question we've found is the json format in the
> FileOutput plugin. I think it exports json that resembles the internal
> data structures but I think it would be possible to output cleaner json.
>
> Have you thought about having output encoders at all? I've seen code
> in the Elasticsearch output that exports simple json I think might
> work so it could be good to share a json decoder between that, the
> FileOutput and a possible S3 output plugin.

Yes, absolutely. This has been on our radar for quite some time, as 
evidenced by this ticket I opened 6 months ago:

https://github.com/mozilla-services/heka/issues/417

We've been thinking about this a lot recently, and our plan is to 
introduce an Encoder plugin type that is analogous to the Decoder type. 
Encoders will take Heka messages as input and will emit raw bytes as 
output. They'll be encapsulated within Outputs the way that Decoders 
are encapsulated within Inputs. There will be a Go interface defined 
for the Encoder plugin type, of course, but we'll provide a 
SandboxEncoder so you can use Lua to do whatever you want, and we'll do 
most of our work there.

This will give us some additional advantages. Right now, for instance, 
the CarbonOutput manages its own TCP connections, and has rudimentary 
keep-alive and reconnection support. But we already have a TcpOutput 
that has much more robust reconnection support, including the use of 
disk queues to ensure we don't lose messages through the disconnect / 
reconnect cycle. Ideally the CarbonOutput would go away, and instead 
you'd use a CarbonEncoder coupled with a TcpOutput, or a UdpOutput, or 
a <Whatever>Output, so all of the transport layer complexity only has 
to be gotten right once.

That ticket has been open for a while, but this is on our short list of 
what's coming next. Not everything in our 0.6 milestone (see 
http://is.gd/azbUSB) will actually make it into the 0.6 release, but 
that one definitely will.

> Are you using Heka to archive log data at mozilla? what format are you
> storing that in if so?

Yes, we're using Heka to parse nginx and rsyslog logs into JSON (we 
ship w/ decoders for these formats: http://is.gd/B2F6qv and 
http://is.gd/sUiE8b) which we're then feeding into ElasticSearch. 
Unfortunately, we're finding that ES is having a hard time keeping up. 
A single machine running both nginx and Heka can produce and parse more 
log data than a cluster of 3 ES nodes on the same hardware can keep up 
with. ES is great, easy to use, and Kibana is awesome, but it may not 
be up to the scale that we need. Or we may be able to find a way to 
have Heka do more aggregation and pre-calc so that we don't have to 
slam ES so hard. Hard to say at this point.

> Thanks,

You're welcome!

-r



> Dan
>
> On 4 March 2014 17:44, Rob Miller <rmiller@mozilla.com
> <mailto:rmiller@mozilla.com>> wrote:
>
>     On Tue 04 Mar 2014 06:26:16 AM PST, Dan wrote:
>
>         Hi,
>
>
>     Hi back!
>
>
>         We are just evaluating Heka for use as our log and metrics
>         aggregation
>         system.
>
>
>     Great! Hope you like what you find.
>
>
>         We would like to archive our logs in S3 so it would be good if
>         Heka could also store batches directly into a bucket.
>
>         Is anyone working on a S3 output plugin for Heka? If not we
>         might look
>         at starting to write one.
>
>
>     I'm not aware of anyone actively working on an S3 output at the
>     moment, no. We have, however, built Cloudwatch plugins, both an
>     input and an output:
>
>     https://github.com/mozilla-__services/heka-mozsvc-plugins/__blob/dev/cloudwatch.go
>     <https://github.com/mozilla-services/heka-mozsvc-plugins/blob/dev/cloudwatch.go>
>
>     Those use the crowdmob fork of Canonical's goamz package to handle
>     the details of interfacing w/ Amazon's API authentication
>     framework. You should be able to use that code as a model to get
>     something bootstrapped pretty easily.
>
>     Our Cloudwatch plugins aren't in the Heka core, they're in a
>     separate repo we set up for plugins that we think would be less
>     widely used. Ultimately we'll probably create a separate repo
>     specifically for AWS related plugins, so the Cloudwatch, S3, and
>     any other Amazon-related plugins that get developed could have a
>     nice cozy home together.
>
>     Hope this helps!
>
>     -r
>
>
```

**Comment by gauteh** [comment]
Marc Fournier writes on July 1, 2015 22:33:
> Hello,
> 
> I'm getting the following exception when running `sup-sync -v`:
> ```
> Adding new message maildir:/home/marc/mailinglists/heka/#new/1435581967.28728_165.host with labels heka,unread,inbox
> /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:727:in `replace_document': DatabaseCorruptError: Db block overwritten - are there multiple writers? (IOError)
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:727:in `block in sync_message'
>         from /home/marc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:639:in `synchronize'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/index.rb:721:in `sync_message'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/poll.rb:215:in `block in poll_from'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
>         from (eval):1:in `poll_from'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:124:in `block in <top (required)>'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:119:in `each'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/gems/sup-0.22.1/bin/sup-sync:119:in `<top (required)>'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/sup-sync:23:in `load'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/sup-sync:23:in `<main>'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/ruby_executable_hooks:15:in `eval'
>         from /home/marc/.rvm/gems/ruby-2.2.1@sup/bin/ruby_executable_hooks:15:in `<main>'
> ```

Hi Marc,

What version of xapian-ruby do you have installed? Perhaps upgrading it
helps?

- gaute

**Comment by mfournier** [comment]
Thanks for taking a look @gauteh !

This is with xapian-ruby 1.2.20, which according to "gem update" is the latest released version. Let me know if I should try with an older version. FWIW, I installed all this by simply running "gem install sup" in a dedicated RVM gemset environment.

**Comment by gauteh** [comment]
Not sure what to do. Is this a fresh sup setup? Maybe it helps to
backup (sup-dump), start with a fresh index (.sup/xapian), then import
the backup (sup-import-dump) after a fresh sup-sync.

- gaute

Marc Fournier writes on July 3, 2015 10:25:

**Comment by mfournier** [comment]
@gauteh I'm now seeing this error more and more frequently, in other cases too. So I guess my index is indeed corrupted.

I'll go through the re-indexation process and get back in case the problem still occurs.

Thanks for you help !
