### ISSUE TITLE
pressing any key after polling is done -> EOFError from thread: poll after loading inbox

### ISSUE THREAD

**Issue by fxkr** [sup-heliotrope/sup#450]
Current develop version. Start sup, everything works normal. As soon as polling is done, pressing any key results in:

```
--- EOFError from thread: poll after loading inbox
EOFError
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:296:in `get_key'
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:43:in `block in from'
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:71:in `new'
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:42:in `from'
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:71:in `to_s'
/home/fxkr/sup-git/lib/sup/crypto.rb:236:in `verified_ok?'
/home/fxkr/sup-git/lib/sup/crypto.rb:281:in `verify'
/home/fxkr/sup-git/lib/sup/util.rb:614:in `method_missing'
/home/fxkr/sup-git/lib/sup/message.rb:429:in `multipart_signed_to_chunks'
/home/fxkr/sup-git/lib/sup/message.rb:469:in `message_to_chunks'
/home/fxkr/sup-git/lib/sup/message.rb:265:in `load_from_source!'
/home/fxkr/sup-git/lib/sup/message.rb:376:in `build_from_source'
/home/fxkr/sup-git/lib/sup/poll.rb:204:in `block in poll_from'
/home/fxkr/sup-git/lib/sup/maildir.rb:161:in `block in poll'
/home/fxkr/sup-git/lib/sup/maildir.rb:160:in `each'
/home/fxkr/sup-git/lib/sup/maildir.rb:160:in `each_with_index'
/home/fxkr/sup-git/lib/sup/maildir.rb:160:in `poll'
/home/fxkr/sup-git/lib/sup/poll.rb:201:in `poll_from'
/home/fxkr/sup-git/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/home/fxkr/sup-git/lib/sup/poll.rb:136:in `each'
/home/fxkr/sup-git/lib/sup/poll.rb:136:in `block in do_poll'
/home/fxkr/sup-git/lib/sup/poll.rb:135:in `synchronize'
/home/fxkr/sup-git/lib/sup/poll.rb:135:in `do_poll'
/home/fxkr/sup-git/lib/sup/util.rb:614:in `method_missing'
/home/fxkr/sup-git/lib/sup/modes/poll_mode.rb:15:in `poll'
/home/fxkr/sup-git/lib/sup/poll.rb:58:in `poll_with_sources'
/home/fxkr/sup-git/lib/sup/poll.rb:94:in `poll'
/home/fxkr/sup-git/lib/sup/util.rb:614:in `method_missing'
bin/sup:207:in `block (2 levels) in <module:Redwood>'
/home/fxkr/sup-git/lib/sup.rb:87:in `block in reporting_thread'
--- NoMethodError from thread: load messages for thread-view-mode
undefined method `user_defined_labels' for nil:NilClass
(eval):1:in `user_defined_labels'
/home/fxkr/sup-git/lib/sup/modes/thread_view_mode.rb:749:in `block in status'
/home/fxkr/sup-git/lib/sup/modes/thread_view_mode.rb:748:in `map'
/home/fxkr/sup-git/lib/sup/modes/thread_view_mode.rb:748:in `status'
/home/fxkr/sup-git/lib/sup/buffer.rb:761:in `get_status_and_title'
/home/fxkr/sup-git/lib/sup/buffer.rb:262:in `draw_screen'
(eval):1:in `draw_screen'
/home/fxkr/sup-git/lib/sup/modes/thread_index_mode.rb:124:in `block in select'
/home/fxkr/sup-git/lib/sup.rb:87:in `block in reporting_thread'
```

**Comment by fxkr** [comment]
So I ran sup-sync and it crashed, but at least it gave me a message ID (of a message from 5 minutes ago):

```
[2015-07-07 12:39:56 +0200] WARNING: problem reading message 01234567.8901234@i_changed_the_mail_id_for_privacy_reasons
/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:296:in `get_key': EOFError (EOFError)
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:43:in `block in from'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:71:in `new'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:42:in `from'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:71:in `to_s'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:236:in `verified_ok?'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:281:in `verify'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:429:in `multipart_signed_to_chunks'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:469:in `message_to_chunks'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:265:in `load_from_source!'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:376:in `build_from_source'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/poll.rb:204:in `block in poll_from'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:124:in `block in <top (required)>'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:119:in `each'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:119:in `<top (required)>'
	from /home/fxkr/bin/sup-sync:23:in `load'
	from /home/fxkr/bin/sup-sync:23:in `<main>'
```

It'd be useful if the filename was also in that message, but that's not a problem.

So I moved that message out of $maildir/new and run sup-sync again, and it doesnt crash anymore, and neither does sup. If I move the message back in sup crashes again, if I move it back out it doesn't.

Unfortunately it's a somewhat private mail; but if it helps I can ask if I can provide it to you.

**Comment by terotil** [comment]
Please, do!

You could also try to anonymize it and/or cut off the private issues and other parts irrelevant to the error (just edit the message file with text editor) and see if you can come up with a minimal message that triggers the bug. That would be helpful.

Judging by the trace, this could be a gpgme problem.

**Comment by gauteh** [comment]
How is gpgme configured to Ask for a passphrase? Perhaps you need to set up
a graphical version of askpass. Do you have a default key set for gpg?

Den tirsdag 7. juli 2015 skrev Tero Tilus <notifications@github.com>
følgende:

**Comment by fxkr** [comment]
Sorry, apparently opening (either during the scan after the poll, or opening the thread in sup) most signed mails trigger this problem, so I picked this one from a public mailing list at random: https://paste.fxkr.net/k8s39v6quw66/1436276983.M252387P15530Q0Ra0e33a947f66f847.localhost - but I think the specific contents don't matter anymore.

Messages I've signed myself don't cause a crash.

Messages with incorrect or unverifiable (missing pubkey...) signatures don't cause a crash.

Signing and encrypting works, gpgme uses pinentry-gtk-2 to ask me for the passphrase. (I didn't manage to find out where to configure that though.)

It worked before, I'm not sure when exactly it stopped working or what might've caused it. But I get signed mails regularly, so it can't have been that long ago.

My gpg.conf (sans comments):

```
require-cross-certification
keyserver  pool.sks-keyservers.net
personal-digest-preferences SHA512
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
default-key  6AB32FCCA5750D48
keyid-format 0xlong
```

**Comment by rakoo** [comment]
It definitely looks like a problem in GPGME:

* `/home/fxkr/.gem/ruby/gems/gpgme-2.0.8/lib/gpgme/signature.rb:71:in 'to_s'` signals that verification was correct
* According to [gpgme doc](https://www.gnupg.org/documentation/manuals/gpgme/Listing-Keys.html), `GPGME::gpgme_get_key` fails with `EOFError` if the key wasn't found.

So gpgme signature verification worked, but it seems gpgme can't retrieve the key.

Just to confirm, could you please run something like this:

```shell
> $ irb
irb(main):001:0> require 'gpgme'
=> true
irb(main):002:0> ctx = GPGME::Ctx.new
=> #<GPGME::Ctx protocol=OpenPGP, armor=false, textmode=false, keylist_mode=local>
irb(main):003:0> ctx.get_key(<offending key id>)
```

This should fail with the same EOFError.

**Comment by fxkr** [comment]
The message I linked to was signed by AFA51BD6CDE573CB and always crashes sup. Works fine in irb though:

```
irb(main):001:0> require 'gpgme'
=> true
irb(main):002:0> ctx = GPGME::Ctx.new
=> #<GPGME::Ctx protocol=OpenPGP, armor=false, textmode=false, keylist_mode=local>
irb(main):003:0> ctx.get_key("AFA51BD6CDE573CB")
=> #<GPGME::Key pub 4096R/CDE573CB 2010-10-29 trust=nil, owner_trust=:unknown, capability=[:encrypt, :sign, :certify, :authenticate], subkeys=[#<GPGME::SubKey sub 4096R/CDE573CB 2010-10-29 trust=nil, capability=[:encrypt, :sign, :certify, :authenticate]>, #<GPGME::SubKey sub 4096R/9A7BDF04 2010-10-29 trust=nil, capability=[:encrypt, :sign, :certify, :authenticate]>], uids=[#<GPGME::UserID Alessandro Ghedini <alessandro@ghedini.me> validity=unknown, signatures=[]>, #<GPGME::UserID Alessandro Ghedini <alexbio@cpan.org> validity=unknown, signatures=[]>, #<GPGME::UserID Alessandro Ghedini <ghedo@debian.org> validity=unknown, signatures=[]>, #<GPGME::UserID Alessandro Ghedini <al3xbio@gmail.com> validity=unknown, signatures=[]>, #<GPGME::UserID Alessandro Ghedini <aghedini@cs.unibo.it> validity=unknown, signatures=[]>]>
```

**Comment by gauteh** [comment]
Have you chosen a key in sup config?

Den tirsdag 7. juli 2015 skrev Felix Kaiser <notifications@github.com>
følgende:

**Comment by fxkr** [comment]
Yes.

```
---
:accounts:
  :default:
    ...
    :gpgkey: '6AB32FCCA5750D48'
...
```

**Comment by gauteh** [comment]
Still an issue?

**Comment by fxkr** [comment]
Not currently.

I've been running sup with gpgme deinstalled for a while now.
Just reinstallled gpgme and can't get it to crash by receive an encrypted email, view encrypted and/or signed mails, etc.

Tested with sup v0.22.1 and git rev 983ca593f59186942d81591adf4c5394739d34b3.

I hope it doesn't start crashing again.

**Comment by gauteh** [comment]
Ok, we got another gpgme issue going #474 related to sending encrypted/signing mails.
