### ISSUE TITLE
Can't run sup-config after gem install

### ISSUE THREAD

**Issue by angezanetti** [sup-heliotrope/sup#453]
I facing many issue to install sup on my Ubuntu 14.04 laptop.
Some deps was missing and not auto-dowloaded during the gem install etc...

So finally after 2 hours of battle with my terminal i got a `1 gem installed` \o/

BUT. The `sup-config` returns:

```
/home/xavier/.rvm/gems/ruby-2.0.0-p643/gems/sup-0.22.1/lib/sup/account.rb:38:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/gems/sup-0.22.1/lib/sup/util.rb:614:in `new'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/gems/sup-0.22.1/lib/sup/util.rb:614:in `init'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/gems/sup-0.22.1/lib/sup.rb:173:in `start'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/gems/sup-0.22.1/bin/sup-config:121:in `<top (required)>'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/bin/sup-config:23:in `load'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/bin/sup-config:23:in `<main>'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /home/xavier/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

Any clue of what's i'm missing here ?

**Comment by gauteh** [comment]
How is your config yaml file? Did you figure out this?

**Comment by gauteh** [comment]
need info
