### ISSUE TITLE
Crash: Poll after loading inbox

### ISSUE THREAD

**Issue by rschulman** [sup-heliotrope/sup#469]
After starting up and the first poll finishing, pushing any key crashes sup with the following:
Perhaps of note, I have just turned on sync_back and run sup-sync-back-maildir on the mailboxes that I care about (eg INBOX only), but sup is still giving me the message to run it every time I start it up.

-- RuntimeError from thread: poll after loading inbox

```
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:615:in `find_docid'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:620:in `find_doc'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:803:in `block in index_message_threading'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:803:in `map'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:803:in `index_message_threading'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/index.rb:717:in `sync_message'
(eval):1:in `sync_message'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:215:in `block in poll_from'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:136:in `each'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:136:in `block in do_poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:135:in `synchronize'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:135:in `do_poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/modes/poll_mode.rb:15:in `poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:58:in `poll_with_sources'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/poll.rb:94:in `poll'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/bin/sup:207:in `block (2 levels) in <module:Redwood>'
/Users/schulmanr/.rvm/gems/ruby-2.1.2/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'
```

**Comment by gauteh** [comment]
Try using sup-sync to fix the problem with the index. This issue exists already on the bug tracker, you should be able to find it by searching for find_docid. Some ways to resolve/work around it are listed there.

**Comment by gauteh** [comment]
#372
