### ISSUE TITLE
Crash when movin around in inbox mode

### ISSUE THREAD

**Issue by hsanson** [sup-heliotrope/sup#470]
This happens so often that makes sup unusable.
Using latest sup master from git.

```
[2015-09-11 07:34:40 +0900] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/ryujin/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- RuntimeError from thread: poll after loading inbox

/home/ryujin/Apps/sup-git/lib/sup/index.rb:615:in `find_docid'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:620:in `find_doc'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:630:in `get_entry'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:639:in `synchronize'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:236:in `build_message'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/home/ryujin/Apps/sup-git/lib/sup/thread.rb:355:in `call'
/home/ryujin/Apps/sup-git/lib/sup/thread.rb:355:in `block in load_thread_for_message'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:230:in `block in each_message_in_thread_for'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:230:in `each'
/home/ryujin/Apps/sup-git/lib/sup/index.rb:230:in `each_message_in_thread_for'
/home/ryujin/Apps/sup-git/lib/sup/thread.rb:353:in `load_thread_for_message'
/home/ryujin/Apps/sup-git/lib/sup/modes/thread_index_mode.rb:798:in `block in add_or_unhide'
/home/ryujin/Apps/sup-git/lib/sup/modes/thread_index_mode.rb:796:in `synchronize'
/home/ryujin/Apps/sup-git/lib/sup/modes/thread_index_mode.rb:796:in `add_or_unhide'
/home/ryujin/Apps/sup-git/lib/sup/modes/thread_index_mode.rb:200:in `handle_added_update'
/home/ryujin/Apps/sup-git/lib/sup/update.rb:26:in `block in relay'
/home/ryujin/Apps/sup-git/lib/sup/update.rb:26:in `each'
/home/ryujin/Apps/sup-git/lib/sup/update.rb:26:in `relay'
(eval):1:in `relay'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:228:in `block in poll_from'
/home/ryujin/Apps/sup-git/lib/sup/maildir.rb:161:in `block in poll'
/home/ryujin/Apps/sup-git/lib/sup/maildir.rb:160:in `each'
/home/ryujin/Apps/sup-git/lib/sup/maildir.rb:160:in `each_with_index'
/home/ryujin/Apps/sup-git/lib/sup/maildir.rb:160:in `poll'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:201:in `poll_from'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:136:in `each'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:136:in `block in do_poll'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:135:in `synchronize'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:135:in `do_poll'
/home/ryujin/Apps/sup-git/lib/sup/util.rb:610:in `method_missing'
/home/ryujin/Apps/sup-git/lib/sup/modes/poll_mode.rb:15:in `poll'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:58:in `poll_with_sources'
/home/ryujin/Apps/sup-git/lib/sup/poll.rb:94:in `poll'
/home/ryujin/Apps/sup-git/lib/sup/util.rb:610:in `method_missing'
bin/sup:207:in `block (2 levels) in <module:Redwood>'
/home/ryujin/Apps/sup-git/lib/sup.rb:87:in `block in reporting_thread'

```

**Comment by gauteh** [comment]
Try using sup-sync to fix the problem with the index. This issue exists already on the bug tracker, you should be able to find it by searching for find_docid. Some ways to resolve/work around it are listed there.

**Comment by gauteh** [comment]
#372

**Comment by hsanson** [comment]
I tried sup-sync but I am being hit by issue #169 so sup-sync also fails for me....

**Comment by gauteh** [comment]
Try to open sup, let it poll and finish completely before you move the cursor around at all.
