### ISSUE TITLE
gpgme 2.0.10 seems to break sup

### ISSUE THREAD

**Issue by gauteh** [sup-heliotrope/sup#471]
from travis:

https://travis-ci.org/sup-heliotrope/sup/jobs/79801351

```
 1) Error:

Redwood::TestCryptoManager#test_sign_and_encrypt:

Redwood::CryptoManager::Error: Exception in GPGME call: Invalid value

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:182:in `rescue in encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:173:in `encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:210:in `sign_and_encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/util.rb:614:in `method_missing'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:80:in `test_sign_and_encrypt'

  2) Error:

Redwood::TestCryptoManager#test_decrypt:

Redwood::CryptoManager::Error: Exception in GPGME call: Invalid value

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:182:in `rescue in encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:173:in `encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/util.rb:614:in `method_missing'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:88:in `test_decrypt'

  3) Error:

Redwood::TestCryptoManager#test_sign:

Redwood::CryptoManager::Error: Exception in GPGME call: Unusable secret key

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:143:in `rescue in sign'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:134:in `sign'

    /home/travis/build/sup-heliotrope/sup/lib/sup/util.rb:614:in `method_missing'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:62:in `test_sign'

  4) Error:

Redwood::TestCryptoManager#test_verify:

Redwood::CryptoManager::Error: Exception in GPGME call: Unusable secret key

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:143:in `rescue in sign'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:134:in `sign'

    (eval):1:in `sign'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:102:in `test_verify'

  5) Error:

Redwood::TestCryptoManager#test_encrypt:

Redwood::CryptoManager::Error: Exception in GPGME call: Invalid value

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:182:in `rescue in encrypt'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:173:in `encrypt'

    (eval):1:in `encrypt'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:72:in `test_encrypt'

  6) Error:

Redwood::TestCryptoManager#test_verify_unknown_keytype:

ArgumentError: NULL pointer given

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:480:in `gpgme_op_sign_result'

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:480:in `sign_result'

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:251:in `rescue in block in sign'

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:248:in `block in sign'

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:79:in `new'

    /home/travis/.rvm/gems/ruby-2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:242:in `sign'

    /home/travis/build/sup-heliotrope/sup/lib/sup/crypto.rb:140:in `sign'

    (eval):1:in `sign'

    /home/travis/build/sup-heliotrope/sup/test/test_crypto.rb:111:in `test_verify_unknown_keytype'
```

**Comment by gauteh** [comment]
Continuing in #474.
