### ISSUE TITLE
Redwood::OutOfSyncSourceError

### ISSUE THREAD

**Issue by osense** [sup-heliotrope/sup#472]
Up until now, sup has been working flawlessly, but I just replied to a message and now, when I attempt to re-open the conversation thread (no new messages have arrived so far), I get this crash:
```
➜  ~  cat .sup/exception-log.txt 
--- Redwood::OutOfSyncSourceError from thread: load messages for thread-view-mode
Redwood::OutOfSyncSourceError
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/message.rb:240:in `location'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/message.rb:268:in `rescue in load_from_source!'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/message.rb:254:in `load_from_source!'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:117:in `block (3 levels) in select'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:70:in `block in each'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:176:in `each_with_stuff'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:178:in `block in each_with_stuff'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:177:in `each'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:177:in `each_with_stuff'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/thread.rb:69:in `each'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:114:in `each_with_index'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:114:in `block (2 levels) in select'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/buffer.rb:700:in `say'
(eval):1:in `say'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:113:in `block in select'
/usr/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup.rb:88:in `block in reporting_thread'
```

**Comment by osense** [comment]
Got that crash twice, and now suddenly it doesn't crash and works as expected. Managed to reproduce it once again, but now no luck (misfortune?) again. Feel free to close this issue as it seems fairly random and easy to deal with (just turn it off and on again - half of which is done for you).

**Comment by gauteh** [comment]
hi, this issue can usually be fixed by running either sup-sync or
letting sup complete a full poll before opening the thread.


Adam Krupicka writes on September 15, 2015 23:23:

**Comment by osense** [comment]
Thanks!
