### ISSUE TITLE
Sup doesn't find any sent mails anymore

### ISSUE THREAD

**Issue by fxkr** [sup-heliotrope/sup#479]
Hi,

to test #450 I used the git version and promptly ran into #467. Luckily I had a backup of my config.yaml. But now, when I send a mail, it doesn't show up in sup anymore.

If someone replies, my mail will show up as `<an unreceived message>`.
If it's an older message it'll show it as `Sup Auto-generated Fake Sender`.
I tried running `sup-sync` and now my inbox is empty. Nooooo!
Additionally, it says `Searching for threads...` now, and if I press *any* key it crashes:

```
--- RuntimeError from thread: load threads for thread-index-mode
invalid source 1
/home/fxkr/sup-git/lib/sup/index.rb:241:in `block in build_message'
/home/fxkr/sup-git/lib/sup/index.rb:239:in `map'
/home/fxkr/sup-git/lib/sup/index.rb:239:in `build_message'
/home/fxkr/sup-git/lib/sup/index.rb:165:in `block (2 levels) in each_id_by_date'
/home/fxkr/sup-git/lib/sup/thread.rb:344:in `call'
/home/fxkr/sup-git/lib/sup/thread.rb:344:in `block in load_n_threads'
/home/fxkr/sup-git/lib/sup/index.rb:165:in `block in each_id_by_date'
/home/fxkr/sup-git/lib/sup/index.rb:288:in `block in each_id'
/home/fxkr/sup-git/lib/sup/index.rb:288:in `each'
/home/fxkr/sup-git/lib/sup/index.rb:288:in `each_id'
/home/fxkr/sup-git/lib/sup/index.rb:165:in `each_id_by_date'
/home/fxkr/sup-git/lib/sup/thread.rb:340:in `load_n_threads'
/home/fxkr/sup-git/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/home/fxkr/sup-git/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/home/fxkr/sup-git/lib/sup.rb:103:in `block in reporting_thread'
```

I have `:sent_source: sup://sent` in `config.yaml`, and here's my `sources.yaml`:

```
---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:///~/.mail
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels: []
- !supmua.org,2006-10-01/Redwood/SentLoader {}
```

Help?

**Comment by gauteh** [comment]
Could be related to #467

**Comment by gauteh** [comment]
Ah, I saw you noticed that already. Did you find the new sources.yaml and config.yaml in .config/sup/? Where is the sent.mbox?

**Comment by fxkr** [comment]
I found sources.yml and config.yaml in .config/sup/, but they seemed to be default files. I restored these from a backup before starting sup again.

**Comment by gauteh** [comment]
Is sent.mbox in .local/share/sup ?

**Comment by fxkr** [comment]
Yes, but it's empty.

**Comment by gauteh** [comment]
@ZJvandeWeg: #401 ping!

**Comment by gauteh** [comment]
Ok. Is the old one still in ~/.sup ?

**Comment by fxkr** [comment]
I'm not sure if it was. It isn't now, but I'm not absolutely sure anymore how I got to that state. (Good that I have a global shell history...)

(I tried to go back to the non-git version, though I think I made things worse. Damn.)

**Comment by gauteh** [comment]
If you go back, you need to restore all the files to ~/.sup.

There was a question when you started the git version the first time, about what to do about the configs. What did you answer there?

**Comment by fxkr** [comment]
Yes, that's what I tried - starting with an empty ~/.sup, merging .local/share/sup and .config/sup into ~/.sup. I'm sure I didn't overwrite any files at that point (mv -i).

`y`.

**Comment by gauteh** [comment]
Weird... @ZJvandeWeg: Is there a race condition where sources and configs are instantiated before the copy, then written after the copy - effectively resetting them?

**Comment by ZJvandeWeg** [comment]
Im unsure how all the files, `config`, `sources` and `mbox` are reset to the default. These should have been copied. 
I would agree there is a race condition. Will look into that later

**Comment by gauteh** [comment]
This and #467 is critical. I have reverted the xdg patches and put them in the xdg branch, for git testers: please move all the content of .config/sup/* and .local/share/sup/* back to ~/.sup.

@ZJvandeWeg: We need more testing on this before we can keep it in develop, we can't risk more data loss.

**Comment by ZJvandeWeg** [comment]
:+1:
