### ISSUE TITLE
Fails to import mail, lib/gpgme/ctx.rb:333:in `get_key': EOFError

### ISSUE THREAD

**Issue by fxkr** [sup-heliotrope/sup#483]
After sup misplaced my sent.mbox yesterday, I redownloaded and reimported my 170000 mails.

I now have 249 mails that sup-sync can't import. (I hacked together a small script that detects this, moves the mail out of the way, and reruns sup-sync.) The stacktrace always looks as follows, possibly with a different call instead of multipart_signed_to_chunks:

```
/home/fxkr/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:333:in `get_key': EOFError (EOFError)
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:43:in `block in from'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:79:in `new'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:42:in `from'
	from /home/fxkr/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:71:in `to_s'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:236:in `verified_ok?'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:281:in `verify'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:429:in `multipart_signed_to_chunks'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:469:in `message_to_chunks'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:265:in `load_from_source!'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:376:in `build_from_source'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/poll.rb:204:in `block in poll_from'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:124:in `block in <top (required)>'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:119:in `each'
	from /home/fxkr/.gem/ruby/gems/sup-0.22.1/bin/sup-sync:119:in `<top (required)>'
	from /home/fxkr/bin/sup-sync:23:in `load'
	from /home/fxkr/bin/sup-sync:23:in `<main>'
```

Here's a mail (from a public mailing list) that triggers the bug: [1], here's a zip-file with all 40 that I have from that list that cause the issue of them, and here's a mail from another public mailing list. Let me know if you need more different ones, I have plenty, but some are private and I'd need to get permission to share first.

[1] https://paste.fxkr.net/zxyk4jq2qh5q/1443256015.M935314P25318Q217R2dbf922f7e905bea.localhost
[2] https://paste.fxkr.net/zxyk4jq2qh5q/sup_issue149_dsa.zip
[3] https://paste.fxkr.net/zxyk4jq2qh5q/1443225364.M162184P22045Q433R624a4e123ceba4cc.localhost

This EOFError looks awfully familiar - see #450 - but now it's in sup-sync not sup itself. Probably the same underlying issue though.

**Comment by rbu** [comment]
I'm having the same issue. I am opening a gpg-signed and encrypted email, pinentry opens and after entering my passphrase correctly, sup first hangs and then crashes on any key input.
```
[2015-11-27 23:50:55 +0100] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/rbu/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- EOFError from thread: load messages for thread-view-mode
EOFError
/home/rbu/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:333:in `get_key'
/home/rbu/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:43:in `block in from'
/home/rbu/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:79:in `new'
/home/rbu/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:42:in `from'
/home/rbu/.gem/ruby/gems/gpgme-2.0.10/lib/gpgme/signature.rb:71:in `to_s'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:236:in `verified_ok?'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/crypto.rb:307:in `decrypt'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:454:in `multipart_encrypted_to_chunks'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:471:in `message_to_chunks'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/message.rb:265:in `load_from_source!'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:117:in `block (3 levels) in select'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:70:in `block in each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:176:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:69:in `each'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:114:in `each_with_index'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:114:in `block (2 levels) in select'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/buffer.rb:700:in `say'
(eval):1:in `say'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:113:in `block in select'
/home/rbu/.gem/ruby/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```

**Comment by rbu** [comment]
This is now happening for me on startup, making the tool completely unsuable.

**Comment by fxkr** [comment]
If you just want to get sup working again really quickly, here are three workarounds:

1. `gem uninstall gpgme`. Sup works fine without crypto support.

2. It's likely that one of your most recently downloaded mails is the culprit, and you'll be able to get sup working again by moving that mail out of the maildir.

  ```
  mkdir ~/one-of-these-mails-is-bad
  cd ~/.mail/new # or wherever you store your mails
  find -cmin -30 -exec mv {} ~/one-of-these-mails-is-bad \;
  # -cmin -30 = last 30 minutes. or use e.g. -ctime -14 for the last 14 days.
  ```

  If sup works again now, you can move the messages back into the maildir one by one (or do binary search ;)) to find out which one crashes sup.

3. Alternatively, try running sup-sync from a recent git version. It'll probably choke on the same message, and since #481 it'll tell you the path of the file it fails on. Depening on how much mail you get this might be faster than workaround no. 2.

**Comment by rbu** [comment]
@fxkr, thanks for responding so quickly. I went with gpgme removal for now, since sending and receiving encrypted email is broken for me anyway. I'll stick to decrypting after saving the message to disk.
Do you have any idea what the root problem is, anything I can do to help?

**Comment by fxkr** [comment]
No, sorry. While I've looked through the sup source code a few times and fixed a few things for myself during the time where sup was unmaintained, I'm just a sup user too and don't really know the codebase.

(I also like to pretend I don't speak Ruby.)
