### ISSUE TITLE
unknown drawable object if archiving many messages

### ISSUE THREAD

**Issue by stain** [sup-heliotrope/sup#486]
I have just set up sup with gmail, offlineimap is active and have imported 9700 messages so far. I have set `archived: true` in `sources.yaml`, but had run `sup-sync` before setting this, and therefore now I want to archive messages by pushing `a`. About 50% of the time, or 100% if I hold down `a` continuously, I get this error after archiving:

```
stain@biggie:~$ sup
--- RuntimeError from thread: poll after loading inbox
unknown drawable object: nil in #<Redwood::InboxMode:0x000000036afec0> for line 56
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/scroll_mode.rb:202:in `draw_line'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/line_cursor_mode.rb:52:in `draw_line'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/scroll_mode.rb:46:in `block in draw'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/scroll_mode.rb:46:in `each'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/scroll_mode.rb:46:in `draw'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/line_cursor_mode.rb:37:in `draw'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/buffer.rb:60:in `draw'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/buffer.rb:44:in `redraw'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/buffer.rb:284:in `draw_screen'
(eval):1:in `draw_screen'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:201:in `handle_added_update'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/update.rb:26:in `block in relay'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/update.rb:26:in `each'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/update.rb:26:in `relay'
(eval):1:in `relay'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:228:in `block in poll_from'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/maildir.rb:161:in `block in poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `each_with_index'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/maildir.rb:160:in `poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:201:in `poll_from'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:136:in `each'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:136:in `block in do_poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:135:in `synchronize'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:135:in `do_poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/modes/poll_mode.rb:15:in `poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:58:in `poll_with_sources'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/poll.rb:94:in `poll'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/bin/sup:207:in `block (2 levels) in <module:Redwood>'
/home/stain/.rvm/gems/ruby-2.1.7/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'
```

Ubuntu 14.04, gnome-terminal.

**Comment by gauteh** [comment]
#261
