### ISSUE TITLE
sup crashes while searching for threads + keypress happens

### ISSUE THREAD

**Issue by inktrap** [sup-heliotrope/sup#491]
I just leave this here for reference. Solution:
sorry guys and girls, invalid source 5 might be something I should investigate. And you guess it right, I edited sources by hand. Yikes.

---

 - If I hit ``U`` sup will search for unread threads.
 - If i press another button, like ``j``, while sup searches, sup crashes.
 - reproducable
 - I run ``sup v0.22.1`` which is included in debian.
 - Log below:
~~~
--- RuntimeError from thread: load threads for thread-index-mode
invalid source 5
/usr/lib/ruby/vendor_ruby/sup/index.rb:241:in `block in build_message'
/usr/lib/ruby/vendor_ruby/sup/index.rb:239:in `map'
/usr/lib/ruby/vendor_ruby/sup/index.rb:239:in `build_message'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `block (2 levels) in each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:344:in `call'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:344:in `block in load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `block in each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `block in each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `each'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:340:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/usr/lib/ruby/vendor_ruby/sup.rb:87:in `block in reporting_thread'
~~~

**Comment by inktrap** [comment]
Closed because ids of sources have to be continuous but were not.
