### ISSUE TITLE
Crash while composing an email in emacs

### ISSUE THREAD

**Issue by onyxrev** [sup-heliotrope/sup#493]
I was composing an email in emacs when sup crashed with the following exception:

```
--- Interrupt from thread: main

/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/buffer.rb:735:in `system'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/buffer.rb:735:in `block in shell_out'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/util/ncurses.rb:238:in `synchronize'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/util/ncurses.rb:238:in `sync'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/buffer.rb:733:in `shell_out'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/util.rb:610:in `method_missing'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/modes/edit_message_mode.rb:269:in `edit_message'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/modes/edit_message_mode.rb:244:in `default_edit_message'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/modes/compose_mode.rb:20:in `default_edit_message'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/lib/sup/modes/compose_mode.rb:34:in `spawn_nicely'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/bin/sup:311:in `<module:Redwood>'
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.22.1/bin/sup:74:in `<top (required)>'
/Users/dan/.rbenv/versions/2.2.2/bin/sup:23:in `load'
/Users/dan/.rbenv/versions/2.2.2/bin/sup:23:in `<main>'
```

**Comment by gauteh** [comment]
After you wrote the file and exited emacs or while emacs was running?

**Comment by gauteh** [comment]
this looks like an emacs issue.
