### ISSUE TITLE
Sup fails to start with new mime-types 3.0

### ISSUE THREAD

**Issue by dangranos** [sup-heliotrope/sup#496]
Archlinux. Trying to start `sup` (installed using `aura -Ayu sup-git`, uses `develop` branch) after update of `ruby-mime-types` to version `3.0-1` results in:

```
/usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'mime-types-data' (~> 3.2015) among 23 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/dangranos/.gem/ruby/2.2.0:/usr/lib/ruby/gems/2.2.0', execute `gem env` for more information
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
        from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
        from /usr/bin/sup:22:in `<main>'
```

**Comment by gauteh** [comment]
maybe you need `mime-types-data`.

Danil Krivonos writes on November 25, 2015 16:04:

**Comment by lamarpavel** [comment]
Same issue here and I can confirm that installing `mime-types-data` fixes this.

**Comment by dangranos** [comment]
I guess i'll have to write about a bug on archforum or on `ruby-mime-types` package. Thanks for the help.

**Comment by gauteh** [comment]
Yup, think this is a bug in ruby-mime-types, if not sup should depend on it.
