### ISSUE TITLE
Problem with adding sources

### ISSUE THREAD

**Issue by sevazhidkov** [sup-heliotrope/sup#499]
I have problems with installing sup by this tutorial: https://github.com/sup-heliotrope/sup/wiki/Running-from-git
It same by this tutorial: https://github.com/sup-heliotrope/sup/wiki/Installation%3A-Debian-and-Ubuntu
Output: 
```
Howdy neighbor! This here's sup-config, ready to help you jack in to
the next generation of digital cyberspace: the text-based email
program. Get ready to be the envy of everyone in your internets
with your amazing keyboarding skills! Jump from email to email with
nary a click of the mouse!
 
Just answer these simple questions and you'll be on your way.
 
What's your name? (enter for "root"): Seva
What's your (primary) email address? (enter for "root@sevazhidkov"): seva@leonardbot.xyz
Ok, your from header will look like this:
  From: Seva <seva@leonardbot.xyz>
 
Do you have any alternate email addresses that also receive email?
If so, enter them now, separated by spaces.
Alternate email addresses:
What file contains your signature? (enter for "/root/.signature"):
What editor would you like to use? (enter for "/usr/bin/vim -f -c 'setlocal spell
spelllang=en_us' -c 'set filetype=mail'"): nanp
Would like to display time in 12h (type 12h) or in 24h (type 24h)?: 24h
 
Now, we'll tell Sup where to find all your email.
Current sources:
  No sources!
 
../sup/bin/sup-config:158:in `<main>': undefined method `choose' for main:Object (NoMethodError)
```
Offlineimap output:
```
OfflineIMAP 6.5.4
  Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync personal:
 *** Processing account personal
 Establishing connection to imap.yandex.ru:143
Folder INBOX [acc: personal]:
 Syncing INBOX: IMAP -> Maildir
Account sync personal:
 *** Finished account 'personal' in 0:01
```
There is INBOX folder in ~/mail/personal

When I'm trying to add source using ``sup-add``, I'm getting this error:
```
root@sevazhidkov:~/sup# bin/sup-add --help
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sup/utils/axe (LoadError)
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from bin/sup-add:8:in `<main>'
```

Ubuntu 14.04

**Comment by sevazhidkov** [comment]
The error is same if i'm using debian package ```sup-mail```

**Comment by gauteh** [comment]
try git now, there seems to a few things we forgot to update when we
started using highline differently.

Seva Zhidkov writes on December 14, 2015 13:08:

**Comment by sevazhidkov** [comment]
thanks, working fine
