### ISSUE TITLE
lag, freeze, crash opening an e-mail

### ISSUE THREAD

**Issue by nanooq** [sup-heliotrope/sup#507]
```
:~$ sup
## [2016-01-29 15:49:17 +0100] ERROR: oh crap, an exception

We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/lora/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
## The Sup Developers

--- IOError from thread: index sync
DatabaseError: inflate failed (invalid distance too far back)
/home/lora/Sync/sup/lib/sup/index.rb:776:in `remove_term'
/home/lora/Sync/sup/lib/sup/index.rb:776:in`block in index_message_locations'
/home/lora/Sync/sup/lib/sup/index.rb:776:in `each'
/home/lora/Sync/sup/lib/sup/index.rb:776:in`index_message_locations'
/home/lora/Sync/sup/lib/sup/index.rb:716:in `sync_message'
/home/lora/Sync/sup/lib/sup/index.rb:141:in`update_message_state'
/home/lora/Sync/sup/lib/sup/index.rb:566:in `run_sync_worker'
/home/lora/Sync/sup/lib/sup/index.rb:553:in`block in start_sync_worker'
/home/lora/Sync/sup/lib/sup.rb:87:in `block in reporting_thread'
```

the result of sup-sync

All report `Scanned 0, added 0, updated 0, deleted 0 messages from $thing`

The behavior remains - nearly the same: 

```
:~$ sup
## [2016-01-29 15:53:46 +0100] ERROR: oh crap, an exception

We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/lora/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
## The Sup Developers

--- RuntimeError from thread: index sync
unknown error in Xapian
/home/lora/Sync/sup/lib/sup/index.rb:776:in `remove_term'
/home/lora/Sync/sup/lib/sup/index.rb:776:in`block in index_message_locations'
/home/lora/Sync/sup/lib/sup/index.rb:776:in `each'
/home/lora/Sync/sup/lib/sup/index.rb:776:in`index_message_locations'
/home/lora/Sync/sup/lib/sup/index.rb:716:in `sync_message'
/home/lora/Sync/sup/lib/sup/index.rb:141:in`update_message_state'
/home/lora/Sync/sup/lib/sup/index.rb:566:in `run_sync_worker'
/home/lora/Sync/sup/lib/sup/index.rb:553:in`block in start_sync_worker'
/home/lora/Sync/sup/lib/sup.rb:87:in `block in reporting_thread'
```

 Any way retrieving better debug informa

**Comment by dhellmann** [comment]
I got this same error and traceback when I tried to open a thread after sup 0.22.1 started polling for new messages. Here's my exception-log.txt:

--- Redwood::OutOfSyncSourceError from thread: load messages for thread-view-mode
Redwood::OutOfSyncSourceError
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/message.rb:240:in `location'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/message.rb:268:in `rescue in load_from_source!'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/message.rb:254:in `load_from_source!'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:117:in `block (3 levels) in select'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:70:in `block in each'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block (2 levels) in each_with_stuff'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:176:in `each_with_stuff'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:178:in `block in each_with_stuff'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:177:in `each_with_stuff'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/thread.rb:69:in `each'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:114:in `each_with_index'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:114:in `block (2 levels) in select'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/buffer.rb:700:in `say'
(eval):1:in `say'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:113:in `block in select'
/Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'

**Comment by gauteh** [comment]
Doug Hellmann writes on February 1, 2016 19:06:
> I got this same error and traceback when I tried to open a thread after sup 0.22.1 started polling for new messages. Here's my exception-log.txt:
> 
> --- Redwood::OutOfSyncSourceError from thread: load messages for thread-view-mode
> Redwood::OutOfSyncSourceError
> /Users/dhellmann/.rvm/gems/ruby-2.2.0/gems/sup-0.22.1/lib/sup/message.rb:240:in `location'

This is not the same error, try running `sup-sync`.

**Comment by dhellmann** [comment]
Ah, I see the traceback looks the same but the error message at the top is different. Since I had the crash a few times in a row, it's not clear whether the out of sync error is the real cause, or a side-effect of the original one. I'll file a new bug if it's a different error the next time it happens.

**Comment by gauteh** [comment]
The OutOfSyncError usually happens if you try to open or do something to
a thread that is changed in the current poll or in the maildir (by
e.g. offlineimap).

**Comment by dhellmann** [comment]
I usually get them right after I poll (or after a poll happens automatically) so that makes sense. Is there any way to guard against them?

**Comment by danc86** [comment]
The original exception reported in this issue: `DatabaseError: inflate failed (invalid distance too far back)` indicates the Xapian database is corrupted. Sup cannot recover from this, the only fix is to use `sup-dump` to back up your Sup labels (if you have any), delete your Sup index, re-index from scratch, and reload labels using `sup-import-dump`.

Unfortunately I don't have any ideas as to what the root cause of this database corruption would be. My best guess is that some earlier Sup process got killed while writing to the Xapian index and corrupted it.

If you have any more details about how the database corruption might have happened, or steps to reproduce, please re-open.
