### ISSUE TITLE
Crash on send: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by maxsone** [sup-heliotrope/sup#524]
I think it's quite possible that I have somehow misconfigured my setup, but the errors do not suggest where to look.  When I try to send a message I have composed, it crashes with 

```
----------------------------------------------------------------
--- TypeError from thread: main
no implicit conversion of nil into String
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:533:in `popen'
/usr/lib/ruby/vendor_ruby/sup/modes/edit_message_mode.rb:533:in `send_message'
/usr/lib/ruby/vendor_ruby/sup/modes/reply_mode.rb:222:in `send_message'
/usr/lib/ruby/vendor_ruby/sup/mode.rb:59:in `handle_input'
/usr/lib/ruby/vendor_ruby/sup/buffer.rb:222:in `handle_input'
/usr/bin/sup-mail:255:in `<module:Redwood>'
/usr/bin/sup-mail:74:in `<main>'
```

I am using msmtp to send mail, and it works okay from the command-line.  Is there anything I can do to resolve this, or is it a bug?

**Comment by danc86** [comment]
This TypeError will happen if you have not filled in any `sendmail` key in your account in `~/.sup/config.yaml`.

Sup should handle this gracefully without crashing.
