### ISSUE TITLE
Crashes with no :default: sender profile

### ISSUE THREAD

**Issue by pangoSE** [sup-heliotrope/sup#533]
Hi

I tried renaming the sender-profiles in my config.yaml and then sup crashed.

**Comment by danc86** [comment]
In `~/.sup/config.yaml`, Sup expects to find a default account named `default` under `accounts`. This key is treated specially and it needs to exist.

I'm assuming you mean that you renamed the `default` key to something else. I tried this just now:

```
:accounts:
  :xdefault:
    :signature: /home/dan/.signature
    :email: djc@djc.id.au
    :name: Dan Callaghan
    ...
```

and Sup indeed does not handle it gracefully.

```
--- NoMethodError from thread: main
undefined method '[]' for nil
/home/dan/sup/lib/sup/account.rb:48:in 'Redwood::AccountManager#add_account'
/home/dan/sup/lib/sup/account.rb:38:in 'Redwood::AccountManager#initialize'
/home/dan/sup/lib/sup/util.rb:594:in 'Class#new'
/home/dan/sup/lib/sup/util.rb:594:in 'Redwood::Singleton::ClassMethods#init'
/home/dan/sup/lib/sup.rb:177:in 'Redwood.start'
bin/sup:145:in '<module:Redwood>'
bin/sup:76:in '<main>'
```

It should give an error message indicating that the `default` account is missing.

**Comment by danc86** [comment]
Sup will still crash, but at least the error gives a better hint what is wrong:

```
--- RuntimeError from thread: main
default account missing in config
/home/dan/sup/lib/sup/account.rb:38:in 'Redwood::AccountManager#initialize'
/home/dan/sup/lib/sup/util.rb:594:in 'Class#new'
/home/dan/sup/lib/sup/util.rb:594:in 'Redwood::Singleton::ClassMethods#init'
/home/dan/sup/lib/sup.rb:177:in 'Redwood.start'
bin/sup:145:in '<module:Redwood>'
bin/sup:76:in '<main>'
```
