### ISSUE TITLE
Crash when syncing messages to gmail (1st time user)

### ISSUE THREAD

**Issue by screech** [sup-heliotrope/sup#543]
The traceback is below. This is happening at start time

/usr/lib/ruby/vendor_ruby/sup/index.rb:615:in `find_docid'
/usr/lib/ruby/vendor_ruby/sup/index.rb:620:in `find_doc'
/usr/lib/ruby/vendor_ruby/sup/index.rb:630:in `get_entry'
/usr/lib/ruby/vendor_ruby/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:639:in `synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:236:in `build_message'
/usr/lib/ruby/vendor_ruby/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:355:in `block in load_thread_for_message'
/usr/lib/ruby/vendor_ruby/sup/index.rb:230:in `block in each_message_in_thread_for'
/usr/lib/ruby/vendor_ruby/sup/index.rb:230:in `each'
/usr/lib/ruby/vendor_ruby/sup/index.rb:230:in `each_message_in_thread_for'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:353:in `load_thread_for_message'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:345:in `block in load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `block in each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `block in each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `each'
/usr/lib/ruby/vendor_ruby/sup/index.rb:288:in `each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:340:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/usr/lib/ruby/vendor_ruby/sup.rb:87:in `block in reporting_thread'

**Comment by screech** [comment]
FWIW .. I blew away the xapian directory, resynced and all is well now
