### ISSUE TITLE
URI error when adding mailsourse with [] symbols

### ISSUE THREAD

**Issue by prudnitskiy** [sup-heliotrope/sup#545]
Trying to add GMail mailbox imported with mbsync but have no luck. Internal GMail folders starts from `[Gmail]`. If I trying to add folder, I'm getting URI error:

```
> sup-add --archive maildir:~/.mail/gmail/\[Gmail\]/.All\ Mail/
[2018-10-03 11:10:45 +0000] Flushing Xapian updates to disk. This may take a while...
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): maildir:~/.mail/gmail/[Gmail]/.All%20Mail/ (URI::InvalidURIError)
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /usr/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
	from /usr/bin/sup-add:97:in `block in <main>'
	from /usr/bin/sup-add:89:in `each'
	from /usr/bin/sup-add:89:in `<main>'
```

versions:

```
OS: Debian 9 x86-64
Ruby: 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
SUP: v0.22.1
```

**Comment by danc86** [comment]
This was fixed as a side effect of commit 3dbb5444b270ab60b70edcd58f6da8d80e9297df.

PR #599 adds a test case to cover this case.
