### ISSUE TITLE
Exception while importing mail

### ISSUE THREAD

**Issue by dbuckalew** [sup-heliotrope/sup#584]
--- NoMethodError from thread: poll after loading inbox
undefined method `getlocal' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:1025:in `default_date_widget_for'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:820:in `date_widget_for_thread'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:866:in `block in update_text_for_line'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:858:in `synchronize'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:858:in `update_text_for_line'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/thread_index_mode.rb:212:in `handle_updated_update'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/update.rb:26:in `block in relay'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/update.rb:26:in `each'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/update.rb:26:in `relay'
(eval):1:in `relay'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/message.rb:317:in `block in sync_back'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/message.rb:316:in `any?'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/message.rb:316:in `sync_back'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/index.rb:699:in `sync_message'
(eval):1:in `sync_message'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:215:in `block in poll_from'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/maildir.rb:161:in `block in poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/maildir.rb:160:in `each'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/maildir.rb:160:in `each_with_index'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/maildir.rb:160:in `poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:201:in `poll_from'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:136:in `each'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:136:in `block in do_poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:135:in `synchronize'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:135:in `do_poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/modes/poll_mode.rb:15:in `poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:58:in `poll_with_sources'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/poll.rb:94:in `poll'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/bin/sup:209:in `block (2 levels) in <module:Redwood>'
/Library/Ruby/Gems/2.6.0/gems/sup-1.0/lib/sup.rb:87:in `block in reporting_thread'

**Comment by IPv2** [comment]
Thank you for reporting this, @dbuckalew.

Two questions please:

- Are you able to re-launch Sup successfully, or does Sup crash again immediately every time?
- Have you noticed a sequence of steps which will reproduce this crash?
