### ISSUE TITLE
Cant get sup properly installed or running, what am i missing?

### ISSUE THREAD

**Issue by PhoenyxCullen** [sup-heliotrope/sup#591]
Currently on Manjaro Linux. Been trying to install and run sup from scratch. I'm now up to the following error. I'm NEW to ruby.

--- FROM THE TERMINAL ---
 allen@mccoy  ~/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.17  sup
/home/allen/.local/share/gem/ruby/3.0.0/gems/lockfile-2.1.3/lib/lockfile.rb:308: warning: finalizer references object to be finalized
[2021-05-15 01:52:56 -0600] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/allen/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- NoMethodError from thread: main
undefined method `encode' for URI:Module
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/mbox.rb:26:in `initialize'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:44:in `initialize'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:22:in `new'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:22:in `default_source'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/bin/sup:168:in `<module:Redwood>'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/bin/sup:76:in `<top (required)>'
/home/allen/.local/share/gem/ruby/3.0.0/bin/sup:23:in `load'
/home/allen/.local/share/gem/ruby/3.0.0/bin/sup:23:in `<main>'
 allen@mccoy  ~/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.17  cat ~/.sup/exception-log.txt 
--- NoMethodError from thread: main
undefined method `encode' for URI:Module
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/mbox.rb:26:in `initialize'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:44:in `initialize'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:22:in `new'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/sent.rb:22:in `default_source'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/bin/sup:168:in `<module:Redwood>'
/home/allen/.local/share/gem/ruby/3.0.0/gems/sup-1.0/bin/sup:76:in `<top (required)>'
/home/allen/.local/share/gem/ruby/3.0.0/bin/sup:23:in `load'
/home/allen/.local/share/gem/ruby/3.0.0/bin/sup:23:in `<main>'

**Comment by PhoenyxCullen** [comment]
Also, ruby 3 was defaulted installed on my machine.

**Comment by PhoenyxCullen** [comment]
<havenwood> schultza: Ah, yeah, you're running into a retirement of a deprecated feature in Ruby 3.0
<havenwood> schultza: They should switch to use CGI.escape.
<havenwood> schultza: In the meantime, use Ruby 2.7.3.
* alexherbo2 (~alexherbo@lmontsouris-659-1-2-186.w193-248.abo.wanadoo.fr) has joined #ruby
<schultza> Ruby 3 was defaulted in my install, I even had to finish installing rubygems package to get to downloading stuff.
<havenwood> schultza: You could forwardport the feature but probably better to fix the lib or use a compatible Ruby version.
* shtirlic (~shtirlic@188.170.72.106) has joined #ruby
<havenwood> schultza: https://github.com/sup-heliotrope/sup/blob/develop/lib/sup/mbox.rb#L26-L39
<havenwood> schultza: require 'cgi'
<havenwood> schultza: Then change those three `URI.encode` to `CGI.escape`.

**Comment by PhoenyxCullen** [comment]
I solved this. I had to completely uninstall ruby3 and install ruby2.7 to get this to work.
