### ISSUE TITLE
just hitting 'j' to move through 40k messages and the whole program crashed

### ISSUE THREAD

**Issue by captain** [sup-heliotrope/sup#612]
```
--- IOError from thread: load threads for thread-index-mode
DatabaseCorruptError: Unexpected end of posting list for 'Kmail'
/usr/lib/ruby/vendor_ruby/sup/index.rb:658:in `mset'
/usr/lib/ruby/vendor_ruby/sup/index.rb:658:in `block in run_query'
/usr/lib/ruby/vendor_ruby/sup/index.rb:652:in `synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:652:in `synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:656:in `run_query'
/usr/lib/ruby/vendor_ruby/sup/index.rb:663:in `run_query_ids'
/usr/lib/ruby/vendor_ruby/sup/index.rb:287:in `each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:340:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/usr/lib/ruby/vendor_ruby/sup.rb:87:in `block in reporting_thread'
```

**Comment by captain** [comment]
Dunno if this is the same bug, but I like the program so far (<1hr using it) except for these crashes.  I hope this will get fixed soon, else I'll need to find another email program.  :-p

```
[2022-09-10 12:22:30 -0500] WARNING: URI.escape is obsolete
[2022-09-10 12:22:30 -0500] WARNING: URI.unescape is obsolete
[2022-09-10 12:22:30 -0500] WARNING: URI.escape is obsolete
[2022-09-10 12:22:30 -0500] WARNING: URI.escape is obsolete
[2022-09-10 12:22:30 -0500] WARNING: URI.escape is obsolete
[2022-09-10 12:23:20 -0500] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/captain/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- IOError from thread: load threads for thread-index-mode
DatabaseCorruptError: Unexpected end of posting list for 'Kmail'
/usr/lib/ruby/vendor_ruby/sup/index.rb:658:in `mset'
/usr/lib/ruby/vendor_ruby/sup/index.rb:658:in `block in run_query'
/usr/lib/ruby/vendor_ruby/sup/index.rb:652:in `synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:652:in `synchronize'
/usr/lib/ruby/vendor_ruby/sup/index.rb:656:in `run_query'
/usr/lib/ruby/vendor_ruby/sup/index.rb:663:in `run_query_ids'
/usr/lib/ruby/vendor_ruby/sup/index.rb:287:in `each_id'
/usr/lib/ruby/vendor_ruby/sup/index.rb:165:in `each_id_by_date'
/usr/lib/ruby/vendor_ruby/sup/thread.rb:340:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/usr/lib/ruby/vendor_ruby/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/usr/lib/ruby/vendor_ruby/sup.rb:87:in `block in reporting_thread'
```

**Comment by danc86** [comment]
I think it means your database was corrupted at some point earlier, sorry. The stack trace doesn't really help to figure out why that would have happened.

Did you get any errors when you first indexed all your mail in sup? Was the `sup-add` process killed abnormally because of a power cut or it crashed or anything unusual like that?

The nuclear option would be to delete your `.sup` directory and reindex your mail from scratch. Obviously you lose any tag changes you have made in sup, including archiving threads. If you do decide to try this, it would be great to capture the full output of `sup-add` and check it carefully to see if sup hit any problems during the indexing.

**Comment by captain** [comment]
Thanks.  Alas, this was a *clean fresh* installation, starting from scratch, so I guess it was delivered to me corrupt.  ¯\_(ツ)_/¯   I miss elm.  elm Just worked®!  ;-)

**Comment by danc86** [comment]
If you have any more details about how the database corruption might have happened, or steps to reproduce, please re-open.

**Comment by danc86** [comment]
I opened a new bug #628 since I found a way to reproduce this.

A key finding is that the database is not actually corrupt when this happens.
