### ISSUE TITLE
Exception encountered on first run

### ISSUE THREAD

**Issue by LightspeedLife** [sup-heliotrope/sup#619]
[exception-log.txt](https://github.com/sup-heliotrope/sup/files/14643844/exception-log.txt)

I had just installed and run `sup` for the first time, following the instructions in
[Installation/Archlinux](https://github.com/sup-heliotrope/sup/wiki/Installation%3A-Archlinux)
and
[New User Guide](https://github.com/sup-heliotrope/sup/wiki/New-User-Guide).

`sup` had this to say on stderr:
```
[2024-03-18 20:39:01 -0400] No 'gpgme' gem detected. Install it for email encryption, decryption and signatures.
/home/brain/.local/share/gem/ruby/3.0.0/gems/lockfile-2.1.3/lib/lockfile.rb:308: warning: finalizer references object to be finalized
[2024-03-18 20:39:02 -0400] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/brain/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- ArgumentError from thread: main
mbox URI ('mbox:///home/brain/.sup/sent.mbox') cannot have a host: 
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/lib/sup/mbox.rb:33:in `initialize'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/lib/sup/sent.rb:44:in `initialize'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/lib/sup/sent.rb:22:in `new'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/lib/sup/sent.rb:22:in `default_source'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/lib/sup/util.rb:585:in `method_missing'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/bin/sup:168:in `<module:Redwood>'
/home/brain/.local/share/gem/ruby/3.0.0/gems/sup-1.1/bin/sup:76:in `<top (required)>'
/home/brain/.local/share/gem/ruby/3.0.0/bin/sup:25:in `load'
/home/brain/.local/share/gem/ruby/3.0.0/bin/sup:25:in `<main>'
```

**Comment by danc86** [comment]
I think this should be fixed by this commit: https://github.com/sup-heliotrope/sup/commit/d2a2a0d7544237a29bf932773cc85e9050bd9c26

I'm planning to release a new version soon, when I've accumulated a few more fixes.

**Comment by danc86** [comment]
Sup 1.2 is released.
