### ISSUE TITLE
Crash doing global find

### ISSUE THREAD

**Issue by zevv** [sup-heliotrope/sup#68]
Another crash, when doing a global find () :

```
[Fri May 24 12:36:30 +0200 2013] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/ico/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that 
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- RuntimeError from thread: load threads for thread-index-mode

./bin/../lib/sup/index.rb:557:in `find_docid'
./bin/../lib/sup/index.rb:562:in `find_doc'
./bin/../lib/sup/index.rb:572:in `get_entry'
./bin/../lib/sup/index.rb:197:in `build_message'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
./bin/../lib/sup/index.rb:581:in `synchronize'
./bin/../lib/sup/index.rb:197:in `build_message'
./bin/../lib/sup/index.rb:191:in `each_message_in_thread_for'
./bin/../lib/sup/thread.rb:349:in `call'
./bin/../lib/sup/thread.rb:349:in `load_thread_for_message'
./bin/../lib/sup/index.rb:191:in `each_message_in_thread_for'
./bin/../lib/sup/index.rb:191:in `each'
./bin/../lib/sup/index.rb:191:in `each_message_in_thread_for'
./bin/../lib/sup/thread.rb:347:in `load_thread_for_message'
./bin/../lib/sup/thread.rb:339:in `load_n_threads'
./bin/../lib/sup/index.rb:152:in `each_id_by_date'
./bin/../lib/sup/index.rb:249:in `each_id'
./bin/../lib/sup/index.rb:249:in `each'
./bin/../lib/sup/index.rb:249:in `each_id'
./bin/../lib/sup/index.rb:152:in `each_id_by_date'
./bin/../lib/sup/thread.rb:334:in `load_n_threads'
./bin/../lib/sup/modes/thread_index_mode.rb:654:in `__unprotected_load_n_threads'
(eval):12:in `load_n_threads'
./bin/../lib/sup/modes/thread_index_mode.rb:638:in `load_n_threads_background'
./bin/../lib/sup.rb:82:in `reporting_thread'
./bin/../lib/sup.rb:80:in `initialize'
./bin/../lib/sup.rb:80:in `new'
./bin/../lib/sup.rb:80:in `reporting_thread'
./bin/../lib/sup/modes/thread_index_mode.rb:637:in `load_n_threads_background'
./bin/../lib/sup/modes/thread_index_mode.rb:708:in `__unprotected_load_threads'
(eval):12:in `load_threads'
./bin/../lib/sup/modes/search_results_mode.rb:48:in `spawn_from_query'
bin/sup:304
```

This is the assert which fails:

```
    fail unless docids.size <= 1
```

**Comment by fxkr** [comment]
Here it is again. (find_docid changed as above)

```
% sup --version       
sup v0.22.1

% sup
[2017-01-05 22:51:34 +0100] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/fxkr/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- RuntimeError from thread: load threads for thread-index-mode
Message ID (message id removed)@mail.gmx.com matches many docs: [841002619, 841002620]
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:616:in `find_docid'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:621:in `find_doc'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:631:in `get_entry'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:236:in `block in build_message'
/usr/share/ruby/monitor.rb:214:in `mon_synchronize'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:640:in `synchronize'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:236:in `build_message'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:355:in `block in load_thread_for_message'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:230:in `block in each_message_in_thread_for'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:230:in `each'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:230:in `each_message_in_thread_for'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:353:in `load_thread_for_message'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:345:in `block in load_n_threads'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:165:in `block in each_id_by_date'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:288:in `block in each_id'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:288:in `each'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:288:in `each_id'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/index.rb:165:in `each_id_by_date'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/thread.rb:340:in `load_n_threads'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/home/fxkr/.gem/ruby/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'
```
